### ISSUE TITLE
Deal with Removal of cgi module from python 3.13

### ISSUE THREAD

**Issue by Anish-M-code** [Anish-M-code/Leaky-LAN#1]
Migrate away from cgi and cgitb asap , refer https://peps.python.org/pep-0594/

**Comment by evil-user** [comment]
@Anish-M-code do you have any plans to work on this issue ? please make such plans public so that end users like me can benefit for such info , also consider migrating to flask or similar framework.

**Comment by Anish-M-code** [comment]
no plans right now , the features which depend on cgi and cgitb modules are expected to be removed .

**Comment by Anish-M-code** [comment]
ReOpening this issue , maybe we can replace cgi with flask .

**Comment by j-karthik** [comment]
@Anish-M-code if possible can you please tag the repository with "hacktoberfest-accepted" or "hacktoberfest" label, I'll create a PR again, Thanks.

**Comment by Anish-M-code** [comment]
@j-karthik now i have tagged this repo as hacktoberfest and hacktoberfest-accepted👍

**Comment by j-karthik** [comment]
@Anish-M-code Thanks, please let me know if anything has to be changed or improved

**Comment by Anish-M-code** [comment]
Thanks for contributing @j-karthik , i have merged the PR , it is good enough for leakylan
