### ISSUE TITLE
improve readme

### ISSUE THREAD

**Issue by Anish-M-code** [Anish-M-code/Leaky-LAN#6]
We must review if we are explaining better what leakylan is and how it might be useful to people , Also currently Images of leakylantool shown in readme is broken.

**Comment by kiranrokkam09** [comment]
I would like to contribute to this issue. Is anybody working with it?

**Comment by sahilsh-dev** [comment]
Yes I am working on it

**Comment by sahilsh-dev** [comment]
I have fixed it

**Comment by Anish-M-code** [comment]
@kiranrokkam09 A similar issue exists in File Analysis Tools here https://github.com/Anish-M-code/File-Analysis-Tool/issues/5 if you are interested .
